version: '3'
services:
  escola-de-musica-vue-app:
    container_name: escola-de-musica-vue-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'  # Mapeia a porta do Vite
    volumes:
      - .:/app  # Monta o diretório atual no container
      - /app/node_modules  # Evita conflitos de dependências
    networks:
      - escola-de-musica-network

networks:
  escola-de-musica-network:
    external: true
